name = "Keeli Company Auxillary Mod"
author = "Keeli Company Aux Team"
prefix = "BNA_KC"
mainprefix = "ORA"

[version]
path = "addons/core/script_version.hpp"
git_hash = 0
[lints.config.file_type]
options.allow_no_extension = true

[files]
include = [
    "mod.cpp",
    "meta.cpp",
    "logo_kcKeeli.png",
    "logo_kcKeeli_ca.paa",
    "LICENSE.md",
    "README.md",
]
exclude = ["*.spp", "*.spp.painter_lock", "*.psd"]

[properties]
author = "Keeli Company Aux Team"
url = "https://github.com/Outer-Rim-Armory/Aux-Mod"

[hemtt.launch.default]
workshop = [
    "2369477168", # ADT
    "623475643",  # 3DEN
    "1779063631", # ZEN
    "2173635424", # 501st Aux Mod
    "1702480117", # 212th Auxiliary Assets
    # "2522638637", # ACE Arsenal Extended
    "2567352444", # WBK Droids # TODO: Move assets to aux itself
    # "2954535667", # Warmantle Armory # Unused
    "767380317", # Blastcore # Only used to test particle effects
    "2061309401", # Last Force Project
    "2291129343", # Improved Melee System
    "2306758518", # Kobra Mod Pack - Legion Studio
    "1393068220", # Kobra Mod Pack - Main
    "2058554822", # 3AS (Beta Test)
    "2215872933", # 3AS Terrains (Beta)
    "769440155", # Operation TREBUCHET
]
presets = ["main"]
dlc = []
optionals = []
mission = "AuxTest.VR"
parameters = []

[hemtt.launch.full]
extends = "default"
workshop = [
    "1572627279", # OPTRE First Contact
    "2915485125", # Burn 'Em
    "2789152015", # WBK Zombies
    "2954535667", # Warmantle Armory # Unused
    "2478080991", # Scion Conflict
    "2323185592", # Lightsabers and Force
    "570118882", # No Weapon Sway
    "2757485942", # Scion Conflict Vehicle Extension
    "3328314886", # Heavy Weapon Framework
    "2918542818", # Sci-fi Support Plus
    "2447965207", # Crows Zeus Additions
    "2387297579", # Zeus Additions
    "2797232351", # Root's Effects - Zeus Module
    "2699465073", # Fire Support Plus
    "2836999643", # Air Support Plus
]
optionals = ["no_burn_screams"]

[hemtt.launch.previews]
extends = "full"
mission = "Previews.VR"
parameters = ["-name=Previews"]
